apiVersion: apps/v1
kind: Deployment
metadata:
  name: ionic-deployment-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ionic-customer
  template:
    metadata:
      labels:
        app: ionic-customer
    spec:
      containers:
      - name: ionic-customer
        image: ghcr.io/ionicerp/customer_fe_angular:latest
        # imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-github-secret
      # - name: my-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ionic-service-customer
spec:
  selector:
    app: ionic-customer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  # type: LoadBalancer
